### ISSUE TITLE
ENH: add line-of-sight TEC support to `gnss_tec` instrument

### ISSUE THREAD

**Issue by aburrell** [pysat/pysatMadrigal#12]
Madrigal provides two types of TEC files.  The first is the VTEC map.  The second, LOS, provides slant TEC.  These files are much larger and should not be loaded in their entirety.  Because this is more complicated, adding this data set is being treated as a separate issue.

When doing this, we need to determine the best way to load the LOS data, and how to best use sat_id to define method.

For help with this, refer to: http://cedar.openmadrigal.org/static/siteSpecific/programming_tips.pdf

**Comment by rstoneback** [comment]
I think that is reasonable.

I saw in the pdf that loading the slant required more memory than many computers have. Do you happen to know what the required footprint is?

**Comment by aburrell** [comment]
No, I was going to look at this today, but decided that it was not a priority.
