### ISSUE TITLE
Restructure Madrigal methods

### ISSUE THREAD

**Issue by aburrell** [pysat/pysatMadrigal#13]
It is a bit silly to have a file named `madrigal.py` in pysatMadrigal.  This file contains the general instrument methods.  Possible ways to rename this file sensibly:

- `pysatMadrigal.instruments.methods.general`,
- `pysatMadrigal.utils.methods`, or
- `pysatMadrigal.instruments.methods` and remove the methods directory.

**Comment by jklenzing** [comment]
I agree that this should be simplified.  My vote would be for `pysatMadrigal.instruments.methods` and remove the methods directory.  I lean toward not moving them to `utils` as these functions are typically not called directly by the user.

The structure in `pysatNASA` has multiple method files, with specialized files for methods unique to certain satellites.  Not sure if we plan to evolve to something similar here, or just keep all the methods in one place.

**Comment by aburrell** [comment]
There may be reason in the future to expand things?  I can't think of one at the moment, though.

**Comment by aburrell** [comment]
Ok, I am currently leaning towards `pysatMadrigal.instruments.methods.general` and moving the "custom" routines in each instrument (the functions ignored by the Instrument class) into `methods`.  This would have implications elsewhere (for consistency). Thoughts?
