### ISSUE TITLE
TST: Expand instrument method coverage

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysatMadrigal#3]
There are a number of additional functions in the instruments here not in the standard output.  Additional tests can be added using the pysat test instruments.

**Comment by aburrell** [comment]
These additional functions are now all in methods:

- [ ] dmsp
- [ ] jro
- [ ] general

**Comment by aburrell** [comment]
Also, need unit tests for:
- [ ] simple file format loading
- [ ] returning a list of files with multiple file formats, unique file times
- [ ] returning a list of files with multiple file formats, non-unique file times

**Comment by aburrell** [comment]
DMSP is addressed in issue #65 .
