### ISSUE TITLE
Unit tests DMSP methods

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysatMadrigal#65]
# Description
Add unit tests for DMSP methods. Example in documentation provides a place to start for running functions.

## Potential impact

- Is the feature related to an existing problem? 
    - Code needs tests.
- How critical is this feature to your workflow? 
- How wide of an impact to you anticipate this enhancement having?
    - Confirms utility of existing functions.
- Would this break any existing functionality?
    - Not likely.

## Potential solution(s)
Add unit tests for the uncovered DMSP methods.

# Alternatives
Leaving as is.

# Additional context
Example in documentation runs some of the functions at hand.

**Comment by aburrell** [comment]
Ok @rstoneback this one is yours!  Let's get the coverage up from 11% 🏇
