### ISSUE TITLE
BUG: list_remote_files and two_digit_year_break

### ISSUE THREAD

**Issue by rstoneback** [pysat/pysatMadrigal#70]
# Description
`pysatMadrigal.general.list_remote_files` only accepts a single input for two_digit_year_break though the use of this keyword may need to vary for different tags. For examples, `gnss_tec` the `vtec` tag has a two digit year in filename, while `site` does not.

# To Reproduce this bug:
1. `gnss = pysat.Instrument("gnss", "tec", 'vtec')`
2. `gnss.remote_file_list(dt.datetime(2020, 12, 1), dt.datetime(2020, 12, 2), user=user, password=password)`
3. See error

Consider including images or test files to help others reproduce the bug and
solve the problem.

## Test configuration
 - OS: MacOS
 - Version Python 3.9
 - Other details about your setup that could be relevant

# Additional context

**Comment by aburrell** [comment]
@rstoneback is this fixed?
